LIBS= hdf5 lmdb protobuf
LIBS+=python3 opencv
LIBS+=lapack-atlas blas-atlas lapack-openblas blas-openblas

LDFLAGS+=$(foreach LIB, ${LIBS}, $(shell pkgconf --libs ${LIB}))
COMMON_FLAGS+=$(foreach LIB, ${LIBS}, $(shell pkgconf --cflags ${LIB}))

PYTHON_LIBRARIES := boost_python3 python3.6m

#
CUSTOM_CXX := g++-7

# CUDA directory contains bin/ and lib/ directories that we need.
CUDA_DIR := /usr/local/cuda

## Refer to http://caffe.berkeleyvision.org/installation.html
# Contributions simplifying and improving our build system are welcome!

# cuDNN acceleration switch (uncomment to build with cuDNN).
USE_CUDNN := 1

CPU_ONLY := 0

# CUDA architecture setting: going with all of them.
# For CUDA < 6.0, comment the *_50 through *_61 lines for compatibility.
# For CUDA < 8.0, comment the *_60 and *_61 lines for compatibility.
# For CUDA >= 9.0, comment the *_20 and *_21 lines for compatibility.
CUDA_ARCH :=	-gencode arch=compute_50,code=sm_50 \
		-gencode arch=compute_52,code=sm_52 \
		-gencode arch=compute_60,code=sm_60 \
		-gencode arch=compute_61,code=sm_61 \
		-gencode arch=compute_61,code=compute_61

# Uncomment to support layers written in Python (will link against Python libs)
WITH_PYTHON_LAYER := 1

# N.B. both build and distribute dirs are cleared on `make clean`
BUILD_DIR := build
DISTRIBUTE_DIR := distribute

# Uncomment for debugging. Does not work on OSX due to https://github.com/BVLC/caffe/issues/171
# DEBUG := 1

# The ID of the GPU that 'make runtest' will use to run unit tests.
TEST_GPUID := 0

# enable pretty build (comment to see full commands)
Q ?= @
